export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
export const INCREMENTCOUNTER = 'incrementCounter'
export const ADDSTUDENTS = 'addstudents'
export const INFOCLICK = 'infoclick'